# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown: kramdown

# Setup
title:               Chinmaya Kr. Patanaik
tagline:             ""
description:         "Master's student, Budding Full Stack Developer, Barca Fan"
url:                 'https://pattu777.github.io'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chinmaya Kr. Patanaik
  url:               https://pattu777.github.com/pattu777.github.io
  email:             patanaikchinmaya@gmail.com
  gravatar:          https://s.gravatar.com/avatar/b5a0ac48d1b8836dc6f679a9003d0dcf?s=80

# Profile links on the left sidebar, leave blank to ignore
social:
  github: pattu777
  #hacker_news: pattu777
  twitter: CPatanaik
  linkedin: chinmayakrpatanaik
  gravatar: b5a0ac48d1b8836dc6f679a9003d0dcf

# Custom vars
version:             1.0.04
gems: [jekyll-paginate, jekyll-sitemap]
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-78081906-1'
