# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown: kramdown

# Setup
title:               Chinmaya's Blog
tagline:             ""
description:         "Budding Full Stack Developer, Barca Fan"
url:                 'http://chinmayapatanaik.com'
baseurl:             ''
paginate:            7

# About/contact
author:
  name:              Chinmaya Kr. Patanaik
  url:               http://chinmayapatanaik.com
  email:             patanaikchinmaya@gmail.com
  gravatar:          https://s.gravatar.com/avatar/b5a0ac48d1b8836dc6f679a9003d0dcf?s=80

# Profile links on the left sidebar, leave blank to ignore
social:
  github: pattu777
  #hacker_news: pattu777
  twitter: CPatanaik
  linkedin: chinmayakrpatanaik
  gravatar: b5a0ac48d1b8836dc6f679a9003d0dcf

# Custom vars
version:             1.0.04
gems: [jekyll-paginate, jekyll-sitemap, jemoji, jekyll-feed]
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
