# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Chinmaya Kr. Patanaik
tagline:             ""
description:         "Master's student, Barca Fan, Python Enthusiast"
url:                 http://pattu777.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chinmaya Kr. Patanaik
  url:               https://pattu777.github.com/pattu777.github.io
  email:             patanaikchinmaya@gmail.com

# Custom vars
version:             1.0.0
